# Generated by Django 6.0.4 on 2026-05-05 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=80, unique=True)),
                ('product_name', models.CharField(max_length=120)),
                ('package_type', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QAStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_code', models.CharField(max_length=50, unique=True)),
                ('station_name', models.CharField(max_length=120)),
                ('line_name', models.CharField(max_length=120)),
                ('camera_endpoint', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_ts', models.DateTimeField()),
                ('lot_number', models.CharField(max_length=120)),
                ('wafer_or_strip_id', models.CharField(blank=True, max_length=120)),
                ('unit_serial', models.CharField(blank=True, max_length=120)),
                ('defect_class', models.CharField(max_length=120)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('bbox_json', models.JSONField(default=dict)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review', 'Review')], max_length=10)),
                ('model_version', models.CharField(max_length=120)),
                ('image_uri', models.CharField(max_length=512)),
                ('overlay_uri', models.CharField(blank=True, max_length=512)),
                ('raw_meta_json', models.JSONField(default=dict)),
                ('final_disposition', models.CharField(blank=True, choices=[('rework', 'Rework'), ('waste', 'Waste'), ('acknowledged', 'Acknowledged')], max_length=20)),
                ('operator_action', models.CharField(blank=True, choices=[('rework', 'Rework'), ('waste', 'Waste'), ('acknowledged', 'Acknowledged')], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defects', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa.productprofile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa.qastation')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'event_ts'], name='qa_defectev_station_95282e_idx'), models.Index(fields=['product', 'defect_class', 'event_ts'], name='qa_defectev_product_dd43f5_idx'), models.Index(fields=['result', 'event_ts'], name='qa_defectev_result_01aada_idx')],
            },
        ),
        migrations.CreateModel(
            name='StationThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_threshold', models.DecimalField(decimal_places=3, default=0.85, max_digits=4)),
                ('nms_threshold', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.productprofile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.qastation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('station', 'product')},
            },
        ),
    ]
