# Generated by Django 6.0.4 on 2026-05-05 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(db_index=True, max_length=120)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_object', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('workstation_id', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-action_timestamp'],
                'permissions': [('export_audit_log', 'Can export audit logs')],
                'indexes': [models.Index(fields=['-action_timestamp'], name='audit_audit_action__d51c9a_idx'), models.Index(fields=['action_type', '-action_timestamp'], name='audit_audit_action__7e3933_idx')],
            },
        ),
    ]
