# Generated by Django 6.0.4 on 2026-05-05 01:55

import apps.training.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_name', models.CharField(help_text="Unique model identifier (e.g., 'IC_Defect_Detection_v1')", max_length=120)),
                ('model_family', models.CharField(default='yolov8', help_text='Model architecture family', max_length=40)),
                ('version_tag', models.CharField(help_text="Semantic version tag (e.g., '1.0.0')", max_length=80)),
                ('defect_types', models.JSONField(default=list, help_text="List of defect classes trained on (e.g., ['scratch', 'crack', 'chip'])")),
                ('primary_format', models.CharField(choices=[('pt', 'PyTorch (.pt)'), ('onnx', 'ONNX'), ('tensorrt', 'TensorRT Engine'), ('openvino', 'OpenVINO'), ('torchscript', 'TorchScript')], default='pt', max_length=20)),
                ('pt_file_path', models.CharField(blank=True, help_text='Path to .pt weights file', max_length=512)),
                ('onnx_file_path', models.CharField(blank=True, max_length=512)),
                ('tensorrt_file_path', models.CharField(blank=True, max_length=512)),
                ('openvino_file_path', models.CharField(blank=True, max_length=512)),
                ('torchscript_file_path', models.CharField(blank=True, max_length=512)),
                ('framework', models.CharField(default='ultralytics', help_text='Framework used (ultralytics, etc)', max_length=40)),
                ('model_size_mb', models.FloatField(default=0.0, help_text='Model file size in MB')),
                ('input_shape', models.JSONField(default=apps.training.models.default_input_shape, help_text='Expected input dimensions')),
                ('metrics_json', models.JSONField(default=dict, help_text='Training metrics (accuracy, precision, recall, F1, mAP50, mAP95)')),
                ('inference_time_ms', models.FloatField(default=0.0, help_text='Avg inference time (ms) on reference hardware')),
                ('throughput_fps', models.FloatField(default=0.0, help_text='Max throughput (FPS) on reference hardware')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('validated', 'Validated'), ('production', 'Production'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Current active model for inference')),
                ('deployed_at', models.DateTimeField(blank=True, help_text='When model moved to production', null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Training notes, calibration details, known limitations')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models_created', to=settings.AUTH_USER_MODEL)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models_promoted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('deploy_ai_model', 'Can deploy AI model to production'), ('export_ai_model', 'Can export AI model to other formats'), ('benchmark_ai_model', 'Can run model benchmarks')],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_name', models.CharField(max_length=120)),
                ('version_tag', models.CharField(max_length=80)),
                ('source_type', models.CharField(default='production_capture', max_length=50)),
                ('class_distribution_json', models.JSONField(default=dict)),
                ('storage_uri', models.CharField(max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_format', models.CharField(default='pt', help_text='Format used for benchmark', max_length=20)),
                ('hardware', models.CharField(choices=[('rtx_4090', 'NVIDIA RTX 4090'), ('rtx_3090', 'NVIDIA RTX 3090'), ('a100', 'NVIDIA A100'), ('cpu', 'CPU (Intel/AMD)'), ('edge_device', 'Edge Device (Jetson/TPU)')], default='rtx_4090', max_length=30)),
                ('inference_time_ms', models.FloatField(help_text='Average inference time (ms)')),
                ('throughput_fps', models.FloatField(help_text='Maximum throughput (FPS)')),
                ('min_latency_ms', models.FloatField(help_text='Minimum latency (ms)')),
                ('max_latency_ms', models.FloatField(help_text='Maximum latency (ms)')),
                ('p95_latency_ms', models.FloatField(help_text='95th percentile latency (ms)')),
                ('memory_usage_mb', models.FloatField(help_text='Peak memory usage (MB)')),
                ('batch_size', models.IntegerField(default=1)),
                ('image_resolution', models.CharField(default='640x640', max_length=20)),
                ('num_test_samples', models.IntegerField(default=1000)),
                ('benchmark_notes', models.TextField(blank=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='training.aimodel')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment_target', models.CharField(help_text="Target deployment location (e.g., 'production', 'staging', 'station_A')", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('inference_requests_count', models.IntegerField(default=0, help_text='Total inference requests processed')),
                ('error_count', models.IntegerField(default=0, help_text='Failed inference requests')),
                ('notes', models.TextField(blank=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='training.aimodel')),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deployed_at'],
                'permissions': [('deploy_model', 'Can deploy model')],
            },
        ),
        migrations.CreateModel(
            name='ModelExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_format', models.CharField(choices=[('onnx', 'ONNX'), ('tensorrt', 'TensorRT Engine'), ('openvino', 'OpenVINO'), ('torchscript', 'TorchScript')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Export'), ('exporting', 'Exporting'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('export_file_path', models.CharField(blank=True, max_length=512)),
                ('export_file_size_mb', models.FloatField(default=0.0)),
                ('export_params_json', models.JSONField(default=dict, help_text='Export parameters (quantization, optimization level)')),
                ('inference_time_ms', models.FloatField(default=0.0, help_text='Benchmark inference time')),
                ('throughput_fps', models.FloatField(default=0.0, help_text='Benchmark throughput')),
                ('memory_usage_mb', models.FloatField(default=0.0, help_text='Peak memory usage during inference')),
                ('benchmark_hardware', models.CharField(default='RTX 4090', help_text='Hardware used for benchmarking', max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='training.aimodel')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('benchmark_export', 'Can benchmark model exports')],
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=120)),
                ('model_family', models.CharField(choices=[('esmd_yolov26n', 'ESMD-YOLOv26n'), ('rtdetr', 'RT-DETR')], max_length=40)),
                ('version_tag', models.CharField(max_length=80)),
                ('framework', models.CharField(default='pytorch', max_length=80)),
                ('weights_uri', models.CharField(max_length=512)),
                ('onnx_uri', models.CharField(blank=True, max_length=512)),
                ('tensorrt_uri', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('production', 'Production'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('metrics_json', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('deploy_model', 'Can deploy model')],
                'unique_together': {('model_name', 'version_tag')},
            },
        ),
        migrations.CreateModel(
            name='ModelAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_access_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.modelregistry')),
            ],
            options={
                'permissions': [('grant_model_access', 'Can grant model access')],
            },
        ),
        migrations.CreateModel(
            name='StationModelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_threshold', models.DecimalField(decimal_places=3, default=0.85, max_digits=4)),
                ('nms_threshold', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.modelregistry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.productprofile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.qastation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('assign_station_model', 'Can assign station model')],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_model_ref', models.CharField(max_length=120)),
                ('output_model_ref', models.CharField(blank=True, max_length=120)),
                ('params_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('logs_uri', models.CharField(blank=True, max_length=512)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.datasetversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active', 'status'], name='training_ai_is_acti_f935ce_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['model_family', 'status'], name='training_ai_model_f_dbf52f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('model_name', 'version_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='datasetversion',
            unique_together={('dataset_name', 'version_tag')},
        ),
        migrations.AddIndex(
            model_name='modelbenchmark',
            index=models.Index(fields=['ai_model', 'hardware'], name='training_mo_ai_mode_8ce515_idx'),
        ),
        migrations.AddIndex(
            model_name='modelbenchmark',
            index=models.Index(fields=['export_format', 'throughput_fps'], name='training_mo_export__ea09a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelbenchmark',
            unique_together={('ai_model', 'export_format', 'hardware')},
        ),
        migrations.AddIndex(
            model_name='modeldeployment',
            index=models.Index(fields=['ai_model', 'status'], name='training_mo_ai_mode_6df25e_idx'),
        ),
        migrations.AddIndex(
            model_name='modeldeployment',
            index=models.Index(fields=['deployment_target', 'status'], name='training_mo_deploym_71fb04_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelexport',
            unique_together={('ai_model', 'export_format')},
        ),
        migrations.AlterUniqueTogether(
            name='modelaccess',
            unique_together={('user', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='stationmodelassignment',
            unique_together={('station', 'product')},
        ),
    ]
